<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

	<title><?php eecho($cfg['APP_NAME']) ?></title>
	<link rel="stylesheet" type="text/css" href="./assets/screen.css" media="screen"/>

</head><body>

<div id="wrapper">

<h1><?php eecho($cfg['APP_NAME']) ?></h1>

